In [1]:
import numpy as np

In [2]:
my_list=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [3]:
my_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [4]:
np.array(my_list)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
my_matrix=([1, 2, 3], [4, 5, 6], [7, 8, 9])

In [7]:
len(my_list)

10

In [8]:
len(my_matrix)

3

In [9]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [5]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones(3)

array([1., 1., 1.])

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [24]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [25]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
np.random.rand(2)

array([0.91441111, 0.75608052])

In [27]:
np.random.rand(5,5)

array([[0.40818634, 0.05777036, 0.05425101, 0.14096794, 0.28012017],
       [0.04837459, 0.25793844, 0.32473308, 0.687533  , 0.53573783],
       [0.96026207, 0.85835097, 0.78047175, 0.74082604, 0.81832281],
       [0.36067714, 0.97486971, 0.32954648, 0.65084743, 0.32422321],
       [0.16314159, 0.3781689 , 0.61717567, 0.16212936, 0.98721638]])

In [28]:
np.random.randn(2)

array([ 0.82960132, -0.63388564])

In [29]:
np.random.randn(5,5)

array([[-1.68982431, -0.31312165, -0.87925644,  0.27146758, -1.83068893],
       [-0.31017355, -1.0679193 ,  0.15254153, -2.07959111,  0.84876981],
       [ 0.6907805 ,  1.36382431,  1.5800399 , -0.58712504, -0.11049358],
       [ 0.89292837, -0.72515847, -0.98407337,  0.80239992, -1.40593333],
       [ 1.22419469,  0.14149482,  0.11257876, -0.85608174, -0.62939465]])

In [31]:
np.random.randint(1,100)

54

In [32]:
np.random.randint(1,100,10)

array([78, 32, 81, 48, 19, 58, 93, 12, 73, 92])

In [35]:
arr=np.arange(25)
ranarr=np.random.randint(0,50,10)

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [38]:
ranarr

array([37, 15, 15,  6, 33, 42, 23, 14, 18, 13])

In [39]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [40]:
ranarr.max()

42

In [42]:
ranarr.argmax()

5

In [43]:
ranarr.min()

6

In [44]:
ranarr.argmin()

3

In [45]:
arr.shape

(25,)

In [46]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [48]:
arr.reshape(1,25).shape

(1, 25)

In [49]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [50]:
arr.reshape(25,1).shape

(25, 1)

In [51]:
arr.dtype

dtype('int64')

In [52]:
ranarr.dtype

dtype('int64')

In [64]:
arr2=np.arange(0,11)

In [54]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
arr2[8]

8

In [56]:
arr2[1:5]

array([1, 2, 3, 4])

In [57]:
# Configurando um valor com intervalo de índice (Transmissão)

In [62]:
arr2[1:5]=100

In [63]:
arr2

array([  0, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [65]:
slice_de_arr=arr2[0:6]

In [66]:
slice_de_arr

array([0, 1, 2, 3, 4, 5])

In [70]:
slice_de_arr[:]=99

In [71]:
slice_de_arr

array([99, 99, 99, 99, 99, 99])

Agora note que as mudanças também ocorrem em nossa matriz original!

In [73]:
arr2

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Os dados não são copiados, é uma visão da matriz original! Isso evita problemas de memória!

In [77]:
# Para obter uma cópia, precisa ser explícito
arr_copy=arr2.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [78]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [79]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [83]:
arr_2d[0]

array([ 5, 10, 15])

In [84]:
arr_2d[0][1]

10

In [85]:
arr_2d[0,1]

10

In [90]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [91]:
arr_2d[2]

array([35, 40, 45])

In [94]:
arr_2d[2,:]

array([35, 40, 45])

In [95]:
arr2d2=np.zeros((10,10))

In [96]:
arr2d2

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [97]:
arr_length=arr2d2.shape[1]

In [106]:
arr_length

10

In [109]:
for i in range(arr_length):
    arr2d2[i] = i
    
arr2d2

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [111]:
#indexação fancy
arr2d2[[2,4,6,7]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

In [112]:
arr2d2[[9,8,7,6]]

array([[9., 9., 9., 9., 9., 9., 9., 9., 9., 9.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.]])

In [114]:
arr=np.arange(0,11)

In [115]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [116]:
arr > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [117]:
bol_arr=arr>4

In [118]:
bol_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [119]:
arr[bol_arr]

array([ 5,  6,  7,  8,  9, 10])

In [122]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [124]:
x=2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

### Operações artiméticas

Você pode facilmente executar operaões aritméticas com matrizes ou escalar. Vamos ver alguns exemplos:

In [126]:
arr=np.arange(0,10)

In [127]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [128]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [129]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [130]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [132]:
# Aviso na divisão por zero, mas não um erro!
# Apenas substituído por 'nan'
arr/arr

/home/pdajgs/python_labs/py3.7/lib/python3.7/site-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [133]:
# Também aviso, mas não um erro, apenas infinito
1/arr

/home/pdajgs/python_labs/py3.7/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [134]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [136]:
# Tomando raízes quadradas
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [137]:
# Calculando exponenciais (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [138]:
# O mesmo que arr.max()
np.max(arr)

9

In [139]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [140]:
np.log(arr)

/home/pdajgs/python_labs/py3.7/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [156]:
arr3=np.zeros((3,3))
arr3_length=arr3.shape[1]

In [158]:
for i in range(arr3_length):
    arr3[i]=i

In [160]:
arr3

array([[0., 0., 0.],
       [1., 1., 1.],
       [2., 2., 2.]])

In [167]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])